# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actionsname: CD workflow

env:
  azure-webapp-name: my-web-app
  bundle-name: angular-app
  node-version: 17.x

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

jobs:
  lint:
    name: Lint (PR)
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
          cache: yarn
      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
          cache: yarn
      - name: Install dependencies
        run: yarn install

      - name: Build app
        run: yarn build

      - name: Upload WebApp package
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.bundle-name }}
          path: dist/github-actions-angular
          if-no-files-found: error

  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
          cahce: yarn
      - name: Install dependencies
        run: yarn install

      - name: Test
        run: yarn ci:test

  deploy:
    name: Deploy Azure WebApp (merge)
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    env:
      bundle-path: ./angular-app/

    steps:
      - name: Download WebApp package
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.bundle-name }}
          path: ${{ env.bundle-path }}

      - name: Deploy Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.azure-webapp-name }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.bundle-path }}

  sonar:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
          cache: yarn
      - name: Install dependencies
        run: yarn install

      - name: Lint reports
        run: yarn generate-lint-reports
      - name: Test coverage reports
        run: yarn generate-test-coverage-reports
      - name: Configure SonarCloud report paths
        run: yarn configure-report-paths
